[package]
name = "symo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.133", features = ["derive"] }
toml = "0.5.8"
chrono = "0.4.19"
interfaces = "0.0.8"
nix = "0.24.1"
kqueue = "1.0.6"
jail = "*"
x11 = "2.19.1"